vcloud:
  type: "object"
  required: true
  patternProperties:
      "^\\w+":
        "$ref": "#/properties/vclouds"
  additionalProperties: false

vclouds:
  type: "object"
  properties:
    host:
      description: "Hostname or IP address of vSphere Server."
      type: "string"
      required: true
    user:
      description: "Authentication user-id for the vSphere Server."
      type: "string"
      required: true
    passwd:
      description: "The password of the specified user."
      type: "string"
      secret: true
      required: true
    ssl_verify:
      description: "SSL Verify."
      type: "boolean"
      required: false

defaults:
  type: "object"
  properties:
    org:
      type: "object"
      properties:
        Settings:
          type: "object"
          properties:
            OrgGeneralSettings:
              type: "object"
              properties:
                CanPublishCatalogs:
                  type: "boolean"
                  required: false
                DeployedVMQuota:
                  type: "integer"
                  required: false
                StoredVmQuota:
                  type: "integer"
                  required: false
                UseServerBootSequence:
                  type: "boolean"
                  required: false
                DelayAfterPowerOnSeconds:
                  type: "integer"
                  required: false
            VAppLeaseSettings:
              type: "object"
              properties:
                DeleteOnStorageLeaseExpiration:
                  type: "boolean"
                  required: false
                DeploymentLeaseSeconds:
                  type: "integer"
                  required: false
                StorageLeaseSeconds:
                  type: "integer"
                  required: false
            OrgPasswordPolicySettings:
              type: "object"
              properties:
                AccountLockoutEnabled:
                  type: "boolean"
                  required: false
                InvalidLoginsBeforeLockout:
                  type: "integer"
                  required: false
                AccountLockoutIntervalMinutes:
                  type: "integer"
                  required: false
            OrgOperationLimitsSettings:
              type: "object"
              properties:
                ConsolesPerVmLimit:
                  type: "integer"
                  required: false
                OperationsPerUser:
                  type: "integer"
                  required: false
                OperationsPerOrg:
                  type: "integer"
                  required: false
            VAppTemplateLeaseSettings:
              type: "object"
              properties:
                DeleteOnStorageLeaseExpiration:
                  type: "boolean"
                  required: false
                StorageLeaseSeconds:
                  type: "integer"
                  required: false
    vdc:
      type: "object"
      properties:
        AllocationModel:
          type: "string"
          required: false
        NetworkQuota:
          type: "integer"
          required: false
        IsThinProvision:
          type: "boolean"
          required: false
        Storage:
          type: "object"
          properties:
            Storage_Profile:
              type: "string"
              required: false
            Limit: 
              type: "integer"
              required: false
            Units:
              type: "string"
              required: false
        ComputeCapacity:
          type: "object"
          properties:
            Cpu:
              type: "object"
              properties:
                Units: 
                  type: "string"
                  required: false
                Allocatedpercent:
                  type: "integer"
                  required: false
                Limit:
                  type: "integer"
                  required: false
            Memory:
              type: "object"
              properties:
                Units:
                  type: "string"
                  required: false
                Allocatedpercent:
                  type: "integer"
                  required: false
                Limit:
                  type: "integer"
                  required: false

