---
name: "Setup org, admin, VDC, vdc Network"
pack: "vcd"
description: "Deploy a Organisation, Admin account, VDC and VDC network"
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "setup_oavn"

criteria:
  trigger.body.vcloud:
    pattern: "^value$"
    type: "exists"
  trigger.body.data:
    pattern: "^value$"
    type: "exists"

action:
  ref: "vcd.setup_org_admin_vdc_vdcnetwork"
  parameters:
    vcloud: "{{trigger.body.vcloud}}"
    data: "{{trigger.body.data}}"
